// African countries and their calling codes
export const africanCountries = [
  { name: 'Nigeria', code: '+234', flag: '🇳🇬' },
  { name: 'South Africa', code: '+27', flag: '🇿🇦' },
  { name: 'Kenya', code: '+254', flag: '🇰🇪' },
  { name: 'Ghana', code: '+233', flag: '🇬🇭' },
  { name: 'Ethiopia', code: '+251', flag: '🇪🇹' },
  { name: 'Tanzania', code: '+255', flag: '🇹🇿' },
  { name: 'Uganda', code: '+256', flag: '🇺🇬' },
  { name: 'Rwanda', code: '+250', flag: '🇷🇼' },
  { name: 'Cameroon', code: '+237', flag: '🇨🇲' },
  { name: 'Ivory Coast', code: '+225', flag: '🇨🇮' },
  { name: 'Senegal', code: '+221', flag: '🇸🇳' },
  { name: 'Morocco', code: '+212', flag: '🇲🇦' },
  { name: 'Egypt', code: '+20', flag: '🇪🇬' },
  { name: 'Algeria', code: '+213', flag: '🇩🇿' },
  { name: 'Tunisia', code: '+216', flag: '🇹🇳' },
  { name: 'Zambia', code: '+260', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: '+263', flag: '🇿🇼' },
  { name: 'Angola', code: '+244', flag: '🇦🇴' },
  { name: 'Mozambique', code: '+258', flag: '🇲🇿' },
  { name: 'Namibia', code: '+264', flag: '🇳🇦' },
].sort((a, b) => a.name.localeCompare(b.name));
